# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Infer the version from the github ref
        id: inferVersion
        run: |
          $prefix = "refs/tags/v"
          if (!${env:GITHUB_REF}.StartsWith($prefix))
          {
              throw "Unexpected GITHUB_REF: ${env:GITHUB_REF}"
          }

          $version = ${env:GITHUB_REF}.Substring($prefix.Length)
          Write-Host "The version is: $version"

          if ($version.Contains("'"))
          {
              throw "Unexpected version containing a single quote: $version"
          }
          if ($version.Contains('"'))
          {
              throw "Unexpected version containing a double quote: $version"
          }
          if ($version.Contains(':'))
          {
              throw "Unexpected version containing a full colon: $version"
          }

          Write-Output "::set-output name=version::$version"
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Clone AASX Package Explorer repository
        run: |
          cd ../
          git clone https://github.com/eclipse-aaspe/package-explorer
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/AasxPluginVws4ls.sln
      - name: Build
        run: dotnet build --no-restore ./src/AasxPluginVws4ls.sln
      - name: Create archive
        run: |
          Rename-Item -Path ".\src\AasxPluginVws4ls\bin\Debug\net6.0-windows" -NewName "AasxPluginVws4ls"
          Compress-Archive -Path .\src\AasxPluginVws4ls\bin\Debug\AasxPluginVws4ls\* -DestinationPath "..\AasxPluginVws4ls-v${{ steps.inferVersion.outputs.version }}.zip"
      - name: Upload release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "../AasxPluginVws4ls-v${{ steps.inferVersion.outputs.version }}.zip"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: "v${{ steps.inferVersion.outputs.version }}"
